### ISSUE TITLE
Release...maybe

### ISSUE THREAD

**Issue by meriturva** [pushrocks/gulp-typings#1]
Hi!
are you going to release a new gulp plugin to make possible integration with "typings"?
so thanks!

**Comment by philkunz** [comment]
Hi, sorry for the late answer. I planned on wrapping the most important functions of typings for gulp, since there is no easy way to use typings programmatically just yet. When the official typings author wants to take over, I'm happy to release the package into his custody. I'll make sure I get started on this tomorrow.
